syms alphaf betaf rhof


Jinv = [1, 0, 0, 0, 0, 0;
        0, 1, 0, 0, 0, 0;
        0, 0, 1, 0, 0, 0;
        1, 0, 0, cos(alphaf)*cos(betaf), -sin(alphaf)*cos(betaf)*rhof, -cos(alphaf)*sin(betaf)*rhof;
        0, 1, 0, sin(alphaf)*cos(betaf), cos(alphaf)*cos(betaf)*rhof,  -sin(alphaf)*sin(betaf)*rhof;
        0, 0, 1, sin(betaf),                      0,                            cos(betaf)*rhof];
    
    A = inv(Jinv);
    
    J = [                                                                                                                                                                1,                                                                                                                                                                0,                                                   0,                                                                                                                                                                 0,                                                                                                                                                                 0,                                                  0;
                                                                                                                                                                0,                                                                                                                                                                1,                                                   0,                                                                                                                                                                 0,                                                                                                                                                                 0,                                                  0;
                                                                                                                                                                0,                                                                                                                                                                0,                                                   1,                                                                                                                                                                 0,                                                                                                                                                                 0,                                                  0;
                    -(cos(alphaf)*cos(betaf))/(cos(alphaf)^2*cos(betaf)^2 + cos(alphaf)^2*sin(betaf)^2 + cos(betaf)^2*sin(alphaf)^2 + sin(alphaf)^2*sin(betaf)^2),                    -(cos(betaf)*sin(alphaf))/(cos(alphaf)^2*cos(betaf)^2 + cos(alphaf)^2*sin(betaf)^2 + cos(betaf)^2*sin(alphaf)^2 + sin(alphaf)^2*sin(betaf)^2),           -sin(betaf)/(cos(betaf)^2 + sin(betaf)^2),                      (cos(alphaf)*cos(betaf))/(cos(alphaf)^2*cos(betaf)^2 + cos(alphaf)^2*sin(betaf)^2 + cos(betaf)^2*sin(alphaf)^2 + sin(alphaf)^2*sin(betaf)^2),                      (cos(betaf)*sin(alphaf))/(cos(alphaf)^2*cos(betaf)^2 + cos(alphaf)^2*sin(betaf)^2 + cos(betaf)^2*sin(alphaf)^2 + sin(alphaf)^2*sin(betaf)^2),           sin(betaf)/(cos(betaf)^2 + sin(betaf)^2);
                                                                                      sin(alphaf)/(rhof*cos(betaf)*cos(alphaf)^2 + rhof*cos(betaf)*sin(alphaf)^2),                                                                                     -cos(alphaf)/(rhof*cos(betaf)*cos(alphaf)^2 + rhof*cos(betaf)*sin(alphaf)^2),                                                   0,                                                                                      -sin(alphaf)/(rhof*cos(betaf)*cos(alphaf)^2 + rhof*cos(betaf)*sin(alphaf)^2),                                                                                       cos(alphaf)/(rhof*cos(betaf)*cos(alphaf)^2 + rhof*cos(betaf)*sin(alphaf)^2),                                                  0;
 (cos(alphaf)*sin(betaf))/(rhof*cos(alphaf)^2*cos(betaf)^2 + rhof*cos(alphaf)^2*sin(betaf)^2 + rhof*cos(betaf)^2*sin(alphaf)^2 + rhof*sin(alphaf)^2*sin(betaf)^2), (sin(alphaf)*sin(betaf))/(rhof*cos(alphaf)^2*cos(betaf)^2 + rhof*cos(alphaf)^2*sin(betaf)^2 + rhof*cos(betaf)^2*sin(alphaf)^2 + rhof*sin(alphaf)^2*sin(betaf)^2), -cos(betaf)/(rhof*cos(betaf)^2 + rhof*sin(betaf)^2), -(cos(alphaf)*sin(betaf))/(rhof*cos(alphaf)^2*cos(betaf)^2 + rhof*cos(alphaf)^2*sin(betaf)^2 + rhof*cos(betaf)^2*sin(alphaf)^2 + rhof*sin(alphaf)^2*sin(betaf)^2), -(sin(alphaf)*sin(betaf))/(rhof*cos(alphaf)^2*cos(betaf)^2 + rhof*cos(alphaf)^2*sin(betaf)^2 + rhof*cos(betaf)^2*sin(alphaf)^2 + rhof*sin(alphaf)^2*sin(betaf)^2), cos(betaf)/(rhof*cos(betaf)^2 + rhof*sin(betaf)^2)];

J_1 = J(1:6,1:3);
J_2 = J(1:6,4:6);

Jinv_1 = pinv(J_1);
Jinv_2 = pinv(J_2);